
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.3/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/GitHub CLI/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/"
    searched_directories:
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build.com"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build.exe"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja-build"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja.com"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja.exe"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/ninja"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu.com"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu.exe"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/samu"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build.com"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build.exe"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja-build"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja.com"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja.exe"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/ninja"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu.com"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu.exe"
      - "C:/Users/Teknoist/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/copilotCli/samu"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/ninja-build.com"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/ninja-build.exe"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/ninja-build"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/ninja.com"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/ninja.exe"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/ninja"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/samu.com"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/samu.exe"
      - "C:/Program Files/Amazon Corretto/jdk21.0.11_10/bin/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/ninja-build.com"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/ninja-build.exe"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/ninja-build"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/ninja.com"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/ninja.exe"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/ninja"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/samu.com"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/samu.exe"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/samu"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build.com"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja.com"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja"
      - "C:/Program Files/Docker/Docker/resources/bin/samu.com"
      - "C:/Program Files/Docker/Docker/resources/bin/samu.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/samu"
      - "C:/Program Files/dotnet/ninja-build.com"
      - "C:/Program Files/dotnet/ninja-build.exe"
      - "C:/Program Files/dotnet/ninja-build"
      - "C:/Program Files/dotnet/ninja.com"
      - "C:/Program Files/dotnet/ninja.exe"
      - "C:/Program Files/dotnet/ninja"
      - "C:/Program Files/dotnet/samu.com"
      - "C:/Program Files/dotnet/samu.exe"
      - "C:/Program Files/dotnet/samu"
      - "C:/Program Files/GitHub CLI/ninja-build.com"
      - "C:/Program Files/GitHub CLI/ninja-build.exe"
      - "C:/Program Files/GitHub CLI/ninja-build"
      - "C:/Program Files/GitHub CLI/ninja.com"
      - "C:/Program Files/GitHub CLI/ninja.exe"
      - "C:/Program Files/GitHub CLI/ninja"
      - "C:/Program Files/GitHub CLI/samu.com"
      - "C:/Program Files/GitHub CLI/samu.exe"
      - "C:/Program Files/GitHub CLI/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Program Files/CMake/bin/ninja-build.com"
      - "C:/Program Files/CMake/bin/ninja-build.exe"
      - "C:/Program Files/CMake/bin/ninja-build"
      - "C:/Program Files/CMake/bin/ninja.com"
      - "C:/Program Files/CMake/bin/ninja.exe"
      - "C:/Program Files/CMake/bin/ninja"
      - "C:/Program Files/CMake/bin/samu.com"
      - "C:/Program Files/CMake/bin/samu.exe"
      - "C:/Program Files/CMake/bin/samu"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/Teknoist/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/ninja-build.com"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/ninja-build.exe"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/ninja-build"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/ninja.com"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/ninja.exe"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/ninja"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/samu.com"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/samu.exe"
      - "C:/Users/Teknoist/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/Scripts/samu"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/ninja-build.com"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/ninja-build.exe"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/ninja-build"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/ninja.com"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/ninja.exe"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/ninja"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/samu.com"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/samu.exe"
      - "C:/Users/Teknoist/AppData/Local/Programs/Lightnovel Crawler/samu"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.com"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build.exe"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/ninja-build"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/ninja.com"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/ninja.exe"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/ninja"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/samu.com"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/samu.exe"
      - "C:/Users/Teknoist/AppData/Local/Programs/Microsoft VS Code/bin/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "c:\\Users\\Teknoist\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
        - "c:\\Users\\Teknoist\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\copilotCli"
        - "C:\\Program Files\\Amazon Corretto\\jdk21.0.11_10\\bin"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\Cloudflare\\Cloudflare WARP\\"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\GitHub CLI\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Users\\Teknoist\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Teknoist\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\Scripts"
        - "C:\\Users\\Teknoist\\AppData\\Local\\Programs\\Lightnovel Crawler"
        - "C:\\Users\\Teknoist\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
...
