#!/usr/bin/env python3
"""Increment shared build counter and regenerate build_version.cpp."""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

_VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")


def write_build_version(output: Path, major: int, minor: int, build: int) -> str:
    version = f"{major}.{minor}.{build}"
    text = f"""// Generated by tools/bump_build_number.py — do not edit.

namespace medicat {{

extern const char kInstallerVersion[] = "{version}";
extern const int kInstallerBuildNumber = {build};

}}  // namespace medicat
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")
    return version


def write_release_tag(repo_root: Path, version: str) -> None:
    """Keep release_tag.txt in lockstep with installer version (GitHub tag = version)."""
    tag_path = repo_root / "release_tag.txt"
    tag_path.write_text(f"{version}\n", encoding="utf-8", newline="\n")


def write_counter(counter_path: Path, major: int, minor: int, build: int) -> str:
    version = f"{major}.{minor}.{build}"
    counter_path.parent.mkdir(parents=True, exist_ok=True)
    counter_path.write_text(f"{version}\n", encoding="utf-8", newline="\n")
    write_release_tag(counter_path.parent, version)
    return version


def parse_version_text(text: str, default_major: int, default_minor: int) -> tuple[int, int, int] | None:
    cleaned = text.strip()
    if not cleaned:
        return None

    match = _VERSION_RE.match(cleaned)
    if match:
        return int(match.group(1)), int(match.group(2)), int(match.group(3))

    if cleaned.isdigit():
        return default_major, default_minor, int(cleaned)

    return None


def read_counter(counter_path: Path, default_major: int, default_minor: int) -> tuple[int, int, int] | None:
    if not counter_path.exists():
        return None
    return parse_version_text(counter_path.read_text(encoding="utf-8"), default_major, default_minor)


def parse_set_value(value: str, default_major: int, default_minor: int) -> tuple[int, int, int] | None:
    parsed = parse_version_text(value, default_major, default_minor)
    if parsed is None:
        return None
    _major, _minor, build = parsed
    if build <= 0:
        return None
    return parsed


def main() -> int:
    parser = argparse.ArgumentParser(description="Bump installer build number")
    parser.add_argument("counter", type=Path, help="Path to version counter file (e.g. 1.0.19)")
    parser.add_argument("output", type=Path, help="Path to generated build_version.cpp")
    parser.add_argument("--major", default="1")
    parser.add_argument("--minor", default="0")
    parser.add_argument(
        "--skip-if-env",
        default="",
        help="Skip bump when this environment variable is set (regenerate output only)",
    )
    parser.add_argument(
        "--set",
        default="",
        help="Force version 1.0.N (or patch N) into build_number.txt, release_tag.txt, and build_version.cpp",
    )
    args = parser.parse_args()

    try:
        default_major = int(args.major)
        default_minor = int(args.minor)
    except ValueError:
        print(f"Invalid --major/--minor: {args.major}.{args.minor}", file=sys.stderr)
        return 1

    pin_from_env = os.environ.get("MEDICAT_PIN_BUILD", "").strip()
    if pin_from_env:
        pinned = parse_set_value(pin_from_env, default_major, default_minor)
        if pinned is None:
            print(f"Invalid MEDICAT_PIN_BUILD: {pin_from_env}", file=sys.stderr)
            return 1
        major, minor, build = pinned
        # Keep build_number.txt / release_tag.txt / cpp in lockstep (tag == version).
        version = write_counter(args.counter, major, minor, build)
        write_build_version(args.output, major, minor, build)
        print(f"Build number pinned (env): {version}")
        return 0

    if args.set.strip():
        pinned = parse_set_value(args.set.strip(), default_major, default_minor)
        if pinned is None:
            print(f"Invalid --set value: {args.set}", file=sys.stderr)
            return 1
        major, minor, build = pinned
        version = write_counter(args.counter, major, minor, build)
        write_build_version(args.output, major, minor, build)
        print(f"Build number pinned: {version}")
        return 0

    if args.skip_if_env and os.environ.get(args.skip_if_env):
        parsed = read_counter(args.counter, default_major, default_minor)
        if parsed is not None:
            major, minor, build = parsed
            version = write_build_version(args.output, major, minor, build)
            write_release_tag(args.counter.parent, version)
            print(f"Build number bump skipped ({args.skip_if_env}); using {version}")
        return 0

    parsed = read_counter(args.counter, default_major, default_minor)
    if parsed is None:
        major, minor, build = default_major, default_minor, 0
    else:
        major, minor, build = parsed

    build += 1
    version = write_counter(args.counter, major, minor, build)
    write_build_version(args.output, major, minor, build)
    print(f"Build number: {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
