#!/usr/bin/env python3
"""Increment shared build counter and regenerate build_version.cpp."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


def write_build_version(output: Path, major: str, minor: str, build: int) -> str:
    version = f"{major}.{minor}.{build}"
    text = f"""// Generated by tools/bump_build_number.py — do not edit.

namespace medicat {{

extern const char kInstallerVersion[] = "{version}";
extern const int kInstallerBuildNumber = {build};

}}  // namespace medicat
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8", newline="\n")
    return version


def main() -> int:
    parser = argparse.ArgumentParser(description="Bump installer build number")
    parser.add_argument("counter", type=Path, help="Path to integer counter file")
    parser.add_argument("output", type=Path, help="Path to generated build_version.cpp")
    parser.add_argument("--major", default="1")
    parser.add_argument("--minor", default="0")
    parser.add_argument(
        "--skip-if-env",
        default="",
        help="Skip bump when this environment variable is set (regenerate output only)",
    )
    args = parser.parse_args()

    if args.skip_if_env and os.environ.get(args.skip_if_env):
        counter_path: Path = args.counter
        build = 0
        if counter_path.exists():
            try:
                build = int(counter_path.read_text(encoding="utf-8").strip())
            except ValueError:
                build = 0
        if build > 0:
            version = write_build_version(args.output, args.major, args.minor, build)
            print(f"Build number bump skipped ({args.skip_if_env}); using {build} ({version})")
        return 0

    counter_path = args.counter
    counter_path.parent.mkdir(parents=True, exist_ok=True)

    build = 0
    if counter_path.exists():
        try:
            build = int(counter_path.read_text(encoding="utf-8").strip())
        except ValueError:
            build = 0

    build += 1
    counter_path.write_text(f"{build}\n", encoding="utf-8", newline="\n")

    version = write_build_version(args.output, args.major, args.minor, build)
    print(f"Build number: {build} ({version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
