#!/usr/bin/env python3
"""Generate obfuscated ingest token source for MedicatInstaller."""

from __future__ import annotations

import sys
from pathlib import Path

# Must match decode in generated/ingest_token.cpp
_KEY = b"MdCtIngest"
_SALT = 41
_SALT_STEP = 13


def obfuscate(token: str) -> list[int]:
    data = token.encode("utf-8")
    out: list[int] = []
    for i, byte in enumerate(data):
        out.append(byte ^ _KEY[i % len(_KEY)] ^ ((i * _SALT_STEP + _SALT) & 0xFF))
    return out


def render_cpp(token: str) -> str:
    obf = obfuscate(token)
    key_bytes = ", ".join(f"0x{b:02x}" for b in _KEY)
    if obf:
        obf_bytes = ", ".join(f"0x{b:02x}" for b in obf)
        obf_array = f"static const unsigned char kIngestObfuscated[] = {{ {obf_bytes} }};"
    else:
        obf_array = "static const unsigned char kIngestObfuscated[] = { 0 };"

    return f"""// Generated by tools/generate_ingest_token.py — do not edit.
#include "ingest_token.h"

#include <string>

namespace medicat {{

namespace {{

{obf_array}
static const unsigned char kIngestKey[] = {{ {key_bytes} }};
static const size_t kIngestObfuscatedLen = {len(obf)};

}}  // namespace

std::string GetIngestToken() {{
    std::string token;
    token.reserve(kIngestObfuscatedLen);
    for (size_t i = 0; i < kIngestObfuscatedLen; ++i) {{
        const unsigned char key = kIngestKey[i % (sizeof(kIngestKey) / sizeof(kIngestKey[0]))];
        const unsigned char salt = static_cast<unsigned char>((i * {_SALT_STEP} + {_SALT}) & 0xFF);
        token.push_back(static_cast<char>(kIngestObfuscated[i] ^ key ^ salt));
    }}
    return token;
}}

bool HasIngestToken() {{
    return kIngestObfuscatedLen > 0;
}}

}}  // namespace medicat
"""


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {Path(sys.argv[0]).name} <token> <output.cpp>", file=sys.stderr)
        return 2

    token = sys.argv[1]
    output = Path(sys.argv[2])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_cpp(token), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
