#!/usr/bin/env python3
"""Generate cpp/src/i18n_generated.h from i18n/translations.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def flatten(obj: dict, prefix: str = "") -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for key, value in obj.items():
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            rows.extend(flatten(value, path))
        else:
            rows.append((path, str(value)))
    rows.sort(key=lambda item: item[0])
    return rows


def escape_cpp(value: str) -> str:
    out: list[str] = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return "".join(out)


def emit_language(lang: str, rows: list[tuple[str, str]]) -> str:
    lines = [f"inline const std::vector<Entry>& Strings_{lang}() {{",
             f"    static const std::vector<Entry> data = {{"]
    for key, value in rows:
        lines.append(f'        {{L"{escape_cpp(key)}", L"{escape_cpp(value)}"}},')
    lines.append("    };")
    lines.append("    return data;")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    src = repo_root / "i18n" / "translations.json"
    out = repo_root / "cpp" / "src" / "i18n_generated.h"

    if not src.exists():
        print(f"Missing translation source: {src}", file=sys.stderr)
        return 1

    data = json.loads(src.read_text(encoding="utf-8"))
    languages = sorted(data.keys())

    chunks = [
        "// Auto-generated by tools/i18n_codegen.py. Do not edit.",
        "#pragma once",
        "#include <string>",
        "#include <vector>",
        "namespace medicat::i18n::generated {",
        "struct Entry {",
        "    const wchar_t* key;",
        "    const wchar_t* value;",
        "};",
    ]

    for lang in languages:
        if not isinstance(data[lang], dict):
            continue
        chunks.append(emit_language(lang, flatten(data[lang])))
        chunks.append("")

    chunks.append("inline const std::vector<Entry>& StringsFor(const std::wstring& lang) {")
    for lang in languages:
        chunks.append(f'    if (lang == L"{lang}") {{ return Strings_{lang}(); }}')
    chunks.append("    return Strings_en();")
    chunks.append("}")
    chunks.append("")
    chunks.append(f"inline const wchar_t* SupportedLanguages[] = {{{', '.join(f'L\"{lang}\"' for lang in languages)}}};")
    chunks.append(f"inline constexpr size_t SupportedLanguageCount = {len(languages)};")
    chunks.append("}  // namespace medicat::i18n::generated")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(chunks) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(languages)} languages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
